---
abstract: 'Lexical Analyzer for Perl5'
author:
  - 'Masaaki Goshima (goccy) <goccy(at)cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
  Module::Build::XSUtil: 0.02
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compiler-Lexer
no_index:
  directory:
    - t
    - examples
    - builder
provides:
  Compiler::Lexer:
    file: lib/Compiler/Lexer.pm
    version: 0.16
  Compiler::Lexer::Kind:
    file: lib/Compiler/Lexer/Constants.pm
  Compiler::Lexer::SyntaxType:
    file: lib/Compiler/Lexer/Constants.pm
  Compiler::Lexer::Token:
    file: lib/Compiler/Lexer/Token.pm
  Compiler::Lexer::TokenType:
    file: lib/Compiler/Lexer/Constants.pm
requires:
  XSLoader: 0.02
  perl: 5.008001
resources:
  bugtracker: https://github.com/goccy/p5-Compiler-Lexer/issues
  homepage: https://github.com/goccy/p5-Compiler-Lexer
  repository: git://github.com/goccy/p5-Compiler-Lexer.git
version: 0.16
x_contributors:
  - 'tokuhirom <tokuhirom@gmail.com>'
  - 'Reini Urban <rurban@cpanel.net>'
  - 'masaaki.goshima <masaaki.goshima@mixi.co.jp>'
  - 'Fumihiro Itoh <fmhrit@gmail.com>'
  - 'Masaaki Goshima <goccy54@gmail.com>'
